[build]
  command = "npm install --force && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_API_URL = "http://localhost:3000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200